### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by stupidyoh** [colmap/colmap#2065]
Hello

I follow installation process
In the part of Configure and compile COLMAP, I got the following error.

**Ninja**
[1/206] Building CXX object src/lib/Si...es/colmap_sift_gpu.dir/SiftMatch.cpp.o
FAILED: src/lib/SiftGPU/CMakeFiles/colmap_sift_gpu.dir/SiftMatch.cpp.o 
/home/vision/bin/ccache /usr/bin/c++ -DCOLMAP_CUDA_ENABLED -DCOLMAP_GUI_ENABLED -DCOLMAP_OPENGL_ENABLED -DCOLMAP_OPENMP_ENABLED -DCUDA_SIFTGPU_ENABLED -DSIFTGPU_NO_DEVIL -I/home/vision/colmap/src -Wno-maybe-uninitialized -w -O3 -DNDEBUG -std=gnu++14 -fPIC -MD -MT src/lib/SiftGPU/CMakeFiles/colmap_sift_gpu.dir/SiftMatch.cpp.o -MF src/lib/SiftGPU/CMakeFiles/colmap_sift_gpu.dir/SiftMatch.cpp.o.d -o src/lib/SiftGPU/CMakeFiles/colmap_sift_gpu.dir/SiftMatch.cpp.o -c /home/vision/colmap/src/lib/SiftGPU/SiftMatch.cpp
In file included from /home/vision/colmap/src/lib/SiftGPU/SiftMatch.cpp:40:
/home/vision/colmap/src/lib/SiftGPU/CuTexImage.h:27:10: fatal error: cuda_runtime.h: No such file or directory
   27 | #include <cuda_runtime.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
[18/206] Building CXX object src/lib/P...p_poisson_recon.dir/PoissonRecon.cpp.o
ninja: build stopped: subcommand failed.

What can I do in this situation?

**Environment:**
 - OS: [Ubuntu 20.04]
 - COLMAP Version [latest]
 - Python : 3.9
 - CUDA : 11.6
 - cmake : 3.26.3

**Comment by Ale-Burzio** [comment]
Bump, same issue

Here's my output from build configuration:

```
cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=native
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options filesystem graph system 
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found FLANN
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libflann.so
-- Found LZ4
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/liblz4.so
-- Found Glog
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
-- Found SQLite3: /usr/include (found version "3.31.1") 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so   
-- Found Glew
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found installed version of gflags: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- Detected gflags version: 2.2.2
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.14.0 installed in: /usr with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
-- Enabling OpenMP support
-- Using header-only CGAL
-- Targetting Ninja
-- Using /usr/bin/c++ compiler.
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so  
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- Found CGAL
--   Includes : /usr/include
--   Libraries : CGAL
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA version 11.7 installed in /usr/local/cuda-11.7 via legacy CMake (<3.17) module. Using the legacy CMake module means that any installation of COLMAP will require that the CUDA libraries are available under LD_LIBRARY_PATH.
-- The CUDA compiler identification is NVIDIA 11.7.99
-- Check for working CUDA compiler: /usr/local/cuda-11.7/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-11.7/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Enabling CUDA support (version: 11.7, archs: native)
-- Found Qt
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
--   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
-- Enabling GUI support
-- Enabling OpenGL support
-- Build type not specified, using Release
-- Enabling SIMD support
-- Disabling interprocedural optimization
-- Disabling ccache support
-- Disabling profiling support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aburzio/colmap/build
```

**Comment by ahojnnes** [comment]
Thanks, this would be caused by the last commit in this dev branch. You can just go back a few days. I'll look into it.

**Comment by ahojnnes** [comment]
Latest commit in dev branch should fix this.

**Comment by MichaelCurrie** [comment]
> Latest commit in dev branch should fix this.

What commit, exactly?  What's the SHA?  I assume you mean this one:  https://github.com/colmap/colmap/commit/e8b8d288ed8b7e41677f8b4b06b7c195cf50d84c

Unfortunately this issue still happens for me with latest code, although it's not clear if it's from the same cause.  I have CUDA 11.7.

It just fails to build, with the error: `ninja: build stopped: subcommand failed.` in my `install-x64-windows-dbg-out.log`  and no other information.  

Although https://github.com/ninja-build/ninja/issues/2378 claims that a more specific error message would be generated to stderr, the file `install-x64-windows-dbg-err.log` is completely empty.  So I don't really have any leads.  I'll try to intercept stderr somehow else...
