### ISSUE TITLE
Colmap Model Aligner Outputs the original Model

### ISSUE THREAD

**Issue by opidopi** [colmap/colmap#2496]
Hello,

I am using the latest version of colmap and attempting to use the colmap model aligner. The output is identical to the original model, it doesn't appear to be to be doing anything at all. I've tried various max error setting and multiple alignment types, all results area the same. Below are some examples of what I'm inputing into the command line. My images are all gps tagged in the exif data and the database.db file contains the gps coordinates. Not sure what I'm doing wrong or if there is some issue with the latest model aligner.

c:\Program Files\COLMAP-3.9.1-windows-cuda>colmap model_aligner \ --input_path C:\SplatData\MassStreetWalkLines\Spatial2\sparse \ --output_path C:\SplatData\MassStreetWalkLines\Spatial2\sparseGeoRef \ --database_path C:\SplatData\MassStreetWalkLines\Spatial2\database.db \ --ref_is_gps 1 \ --alignment_type ecef \ --alignment_max_error 1
I20240407 11:08:26.539500 15472 model.cc:122]
Converting Alignment Coordinates from GPS (lat/lon/alt) to ECEF.
I20240407 11:08:27.063509 15472 misc.cc:205]
Aligning reconstruction to ecef
-------------------------------
I20240407 11:08:27.063509 15472 model.cc:347] => Using 64 reference images
I20240407 11:08:27.070509 15472 model.cc:367] => Alignment error: 6368478.485814 (mean), 6368476.467385 (median)
I20240407 11:08:27.070509 15472 model.cc:405] => Alignment succeeded

c:\Program Files\COLMAP-3.9.1-windows-cuda>colmap model_aligner \ --input_path C:\SplatData\MassStreetWalkLines\Spatial2\sparse \ --output_path C:\SplatData\MassStreetWalkLines\Spatial2\sparseGeoRef \ --database_path C:\SplatData\MassStreetWalkLines\Spatial2\database.db \ --ref_is_gps 1 \ --alignment_type ecef \ --alignment_max_error 100
I20240407 11:08:35.207886 17092 model.cc:122]
Converting Alignment Coordinates from GPS (lat/lon/alt) to ECEF.
I20240407 11:08:35.734954 17092 misc.cc:205]
Aligning reconstruction to ecef
-------------------------------
I20240407 11:08:35.735954 17092 model.cc:347] => Using 64 reference images
I20240407 11:08:35.738956 17092 model.cc:367] => Alignment error: 6368478.485814 (mean), 6368476.467385 (median)
I20240407 11:08:35.739955 17092 model.cc:405] => Alignment succeeded

**Comment by xiemeilong** [comment]
Same issue.

**Comment by ahojnnes** [comment]
This is fixed in the latest commits in the main branch but not yet released with a new official version. You can compile manually to prevent the issue.

**Comment by zjtde1990** [comment]
> This is fixed in the latest commits in the main branch but not yet released with a new official version. You can compile manually to prevent the issue.

@ahojnnes I used the latestcodes in main branch, but I still have this problem. What can I do to fix it?

**Comment by ahojnnes** [comment]
Closing: model aligner bug fixed in latest main branch per maintainer.
