### ISSUE TITLE
Python bindings and undefined symbol

### ISSUE THREAD

**Issue by senyai** [colmap/colmap#3665]
Hi!

I'm trying to build pycolmap with CUDA. But I get this error:

```
INTEL MKL ERROR: /lib/x86_64-linux-gnu/libmkl_avx512.so: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_avx512.so or libmkl_def.so.
ninja: build stopped: subcommand failed.
```
What I found is that `libmkl_avx512.so` requires `mkl_sparse_optimize_bsr_trsm_i8` symbol, but it is defined in a library that is not linked. Can it be cmake issue?

Here's my Dockerfile. It fails on the last step. Any tips are very much appreciated!

```Dockerfile
ARG UBUNTU_VERSION=24.04
ARG NVIDIA_CUDA_VERSION=12.9.1

FROM nvidia/cuda:${NVIDIA_CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION} AS builder

ENV DEBIAN_FRONTEND=noninteractive
ENV QT_XCB_GL_INTEGRATION=xcb_egl

#
# INSTALL COMMON SYSTEM MODULES
#

RUN apt-get update && \
    apt-get install -y \
    curl \
    wget \
    vim \
    build-essential \
    git \
    cmake \
    ninja-build \
    libboost-program-options-dev \
    libboost-graph-dev \
    libboost-system-dev \
    libeigen3-dev \
    libfreeimage-dev \
    libmetis-dev \
    libgoogle-glog-dev \
    libgtest-dev \
    libgmock-dev \
    libsqlite3-dev \
    libglew-dev \
    qt6-base-dev \
    libqt6opengl6-dev \
    libqt6openglwidgets6 \
    libcgal-dev \
    libceres-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libmkl-full-dev \
    python3 \
    python3-pip \
    python3-dev \
    python-is-python3
# \
#    && apt-get clean \
#    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

#
# BUILD AND INSTALL NUMPY
#

RUN git clone --depth=1 --recursive https://github.com/numpy/numpy --branch v2.3.4

RUN cd numpy && \
    pip install --break-system-packages -r requirements/build_requirements.txt && \
    pip install --break-system-packages --no-build-isolation .

#
# BUILD AND INSTALL COLMAP
#

ARG COLMAP_GIT_COMMIT=cf1b2666727fa3e31f6e19a71c2b4857d356e74a
# use `nvidia-smi --query-gpu=name,compute_cap --format=csv` to get your architecture
ARG CUDA_ARCHITECTURES=70
RUN git clone https://github.com/colmap/colmap.git
RUN cd colmap && \
    git fetch https://github.com/colmap/colmap.git ${COLMAP_GIT_COMMIT} && \
    git checkout FETCH_HEAD && \
    mkdir build && \
    cd build && \
    cmake .. \
        -GNinja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CUDA_ARCHITECTURES=${CUDA_ARCHITECTURES} \
        -DCMAKE_INSTALL_PREFIX=/build/colmap-install \
        -DBLA_VENDOR=Intel10_64lp && \
    ninja install

RUN pip install --break-system-packages \
    scikit-build-core>=0.3.3 \
    pybind11==3.0.1 \
    'pybind11_stubgen @ git+https://github.com/sarlinpe/pybind11-stubgen@sarlinpe/fix-2025-08-20'

RUN cd /build/colmap && \
    CMAKE_ARGS='-Dcolmap_DIR=/build/colmap-install/share/colmap/ -DBLA_VENDOR=Intel10_64lp' pip install --break-system-packages --no-build-isolation .
```

**Comment by unclearness** [comment]
I encountered this same error on Ubuntu 24.04, Xeon w7-3465X, and colmap/pycolmap 3.13.0, though for me it happened at runtime during the SfM step. Interestingly, it consistently crashed during Bundle Adjustment with datasets larger than 50 images (likely due to an algorithm switch at that threshold).

I solved it by switching the CMake flag from `Intel10_64lp` suggested in the official installation document to `Intel10_64_dyn` 

`cmake .. -GNinja -DBLA_VENDOR=Intel10_64_dyn`

**Comment by ahojnnes** [comment]
Closing: MKL linking resolved with Intel10_64_dyn.

**Comment by TannerGilbert** [comment]
@unclearness can you provide more details on your fix. I changed `Intel10_64lp` to `Intel10_64_dyn` as you suggested when building Colmap:

```
RUN cd /colmap && \
    mkdir -p build/.ccache && \
    cd build && \
    cmake .. \
        -GNinja \
        -DCMAKE_CUDA_ARCHITECTURES=${CUDA_ARCHITECTURES} \
        -DCMAKE_INSTALL_PREFIX=/colmap-install \
        -DFETCHCONTENT_FULLY_DISCONNECTED=${FETCHCONTENT_FULLY_DISCONNECTED} \
        -DBLA_VENDOR=Intel10_64_dyn && \
    ninja install
```

but I'm still facing the issue after that (using the provided Colmap Dockercontainer)

**Comment by TannerGilbert** [comment]
I managed to solve the issue for me by installing `intel-oneapi-mkl` in the runtime stage of the container instead of `libmkl`. This package seems to be a lot more activaly maintained as the latest version of [`libmkl-core` for debian is 2020.4.304-7](https://packages.debian.org/sid/libs/libmkl-core). @ahojnnes do you think I should add this change to #4223?

**Comment by unclearness** [comment]
@TannerGilbert 
For reference, here is the full set of commands that worked in my environment (Ubuntu installed directly on my machine, not inside Docker):

```bash
# Build COLMAP
export colmap_DIR="$PWD"/colmap/install_local/
cd colmap
rm -rf build_local install_local
mkdir build_local
cd build_local

# -DBLA_VENDOR=Intel10_64lp, as described in the official documentation,
# may crash on some systems.
# cmake .. -GNinja -DBLA_VENDOR=Intel10_64lp
cmake .. -GNinja -DBLA_VENDOR=Intel10_64_dyn
ninja

# Install COLMAP to a local directory so it does not interfere with the system COLMAP
cmake --install . --prefix "$colmap_DIR"
cd ../..
```

I only verified this on my native Ubuntu environment, so I cannot confirm whether the same fix is sufficient for the provided Docker container.

For debugging, I also checked the BLAS/LAPACK setup on my machine. `update-alternatives` shows that the default `libblas.so` / `liblapack.so` resolve to OpenBLAS, while `ldd` on pycolmap also shows `libmkl_rt.so` at runtime. So in my environment, both OpenBLAS and MKL-related libraries are visible, and the issue may depend on how the BLAS/LAPACK backend is resolved in a given setup.

```bash
XXXXX$ find path_to_venv/.venv/lib/python3.11/site-packages/pycolmap -name '*.so' -exec ldd {} \; | grep -Ei 'mkl|openblas|blas|lapack'
        libmkl_rt.so => /lib/x86_64-linux-gnu/libmkl_rt.so (0x00007adfe2800000)
        liblapack.so.3 => /lib/x86_64-linux-gnu/liblapack.so.3 (0x00007adfe1800000)
        libblas.so.3 => /lib/x86_64-linux-gnu/libblas.so.3 (0x00007adfe0797000)
        libopenblas.so.0 => /lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007adfde3b0000)
```

**Comment by TannerGilbert** [comment]
@unclearness thanks for the detailed reply. Will look into it again in a couple of days.

**Comment by Anand-EB** [comment]
I had a similar issue, although during runtime and not during build.  When running global_mapper, I get the following error -
```
I0323 09:57:03.324569 20538 global_mapper.cc:465] === Running rotation averaging ===
INTEL MKL ERROR: /lib/x86_64-linux-gnu/libmkl_avx512.so: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_avx512.so or libmkl_def.so.
```
I compiled with `-DBLA_VENDOR=Intel10_64_dyn` upon a ubuntu22.04 base image and I am using Colmap version 4.0.2.
I am using ` Intel(R) Xeon(R) Gold 6448Y` CPU and `libmkl` version is 

```
$apt-cache policy libmkl-full-dev
libmkl-full-dev:
  Installed: (none)
  Candidate: 2020.4.304-2ubuntu3
  Version table:
     2020.4.304-2ubuntu3 500
```

A solution is to set the LD_PRELOAD
```
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libmkl_def.so:/usr/lib/x86_64-linux-gnu/libmkl_avx2.so:/usr/lib/x86_64-linux-gnu/libmkl_core.so:/usr/lib/x86_64-linux-gnu/libmkl_intel_lp64.so:/usr/lib/x86_64-linux-gnu/libmkl_intel_thread.so:/usr/lib/x86_64-linux-gnu/libiomp5.so
```
For some reason these *.so files are not loaded when required. 

Source for this fix: https://bugs.launchpad.net/ubuntu/+source/intel-mkl/+bug/1947626
