### ISSUE TITLE
issues with freeimageio and dense reconstruction

### ISSUE THREAD

**Issue by plusk01** [colmap/colmap#3809]
**Describe the bug**
Undistortion of single-channel greyscale images (both jpg / png) results in incorrect output. Bug introduced by #3459 (works fine on prior commit). Likely a memory buffer / stride issue.

Unrelated to greyscale imagery (tried on fresh south building dataset), attempting to generate depth maps by clicking 'Stereo' yields
```
==============================================================================
Processing view 127 / 128 for P1180219.JPG
==============================================================================
E20251208 02:07:54.936579 17538 bitmap.cc:50] 'dynamic_cast<OIIOMetaData*>(meta_data)' Must be non NULL
I20251208 02:07:54.936589 17538 misc.cc:44] 
==============================================================================
Processing view 128 / 128 for P1180198.JPG
==============================================================================
E20251208 02:07:54.936592 17538 bitmap.cc:50] 'dynamic_cast<OIIOMetaData*>(meta_data)' Must be non NULL
I20251208 02:07:54.936600 17527 timer.cc:90] Elapsed time: 0.004 [minutes]
```

**To Reproduce**
1. Download south building dataset
2. Use GIMP to convert an image to greyscale
3. Start colmap gui
4. Import sparse reconstruction model
5. Double check Inspect Database to ensure that input image is greyscale.
6. Dense reconstruction, select model
7. Run Undistortion
8. View undistorted image

**Screenshots**
_Input_
![Image](https://github.com/user-attachments/assets/5171b1b0-019a-4dec-8248-7db61d4f1879)

_Undistorted_
![Image](https://github.com/user-attachments/assets/414dafdb-9d01-4392-a4c4-307d21887485)

**Environment:**
 - OS: Ubuntu
 - COLMAP Version 145baccaace9b8a46df8ac0cb9ca353585484d5a

**Comment by Parskatt** [comment]
Can reproduce this on most recent `pycolmap` wheels with CUDA.

**Comment by ahojnnes** [comment]
Thank you for reporting the issue. Should be fixed with: https://github.com/colmap/colmap/pull/3812

**Comment by ahojnnes** [comment]
Appreciate if you can confirm and close in case it successfully fixes the issue also on your end.

**Comment by plusk01** [comment]
thx - greyscale undistortion issue resolved

However, still see the following when trying to patch match on [e117f9c](https://github.com/colmap/colmap/commit/e117f9c1ab2d60a8a9c40145d0ca86fb1e8583b6)

```
==============================================================================
Processing view 127 / 128 for P1180219.JPG
==============================================================================
E20251210 02:49:20.015167 1122632 bitmap.cc:50] 'dynamic_cast<OIIOMetaData*>(meta_data)' Must be non NULL
I20251210 02:49:20.015178 1122632 misc.cc:44] 
==============================================================================
Processing view 128 / 128 for P1180198.JPG
==============================================================================
E20251210 02:49:20.015182 1122632 bitmap.cc:50] 'dynamic_cast<OIIOMetaData*>(meta_data)' Must be non NULL
I20251210 02:49:20.015192 1122629 timer.cc:90] Elapsed time: 0.004 [minutes]
```

**Comment by B1ueber2y** [comment]
The error was raised here https://github.com/colmap/colmap/blob/main/src/colmap/mvs/patch_match.cc#L435 due to invalid copying behavior of empty bitmap. Should be fixed in the linked PR.
