### ISSUE TITLE
How to remove random factor from mapper?

### ISSUE THREAD

**Issue by is03wlei** [colmap/colmap#404]
I changed the random seed to constant.
But still got different result for each running.

void SetPRNGSeed(unsigned seed) {
  // Overwrite existing PRNG
  if (PRNG != nullptr) {
    delete PRNG;
  }

  if (seed == kRandomPRNGSeed) {
    /*seed = static_cast<unsigned>(
        std::chrono::system_clock::now().time_since_epoch().count());*/
    seed = 99995039;
  }

  PRNG = new std::mt19937(seed);
}

**Comment by ahojnnes** [comment]
You could try to also set srand(0).

**Comment by is03wlei** [comment]
I didn't see randomization in Ceres. My ceres version is 1.12.0.
All randomization happens in tests.
Could you give more suggests to remove randomization?
I need to make result reproducible.

pwd
ceres-solver-1.12.0/internal/ceres
grep srand . -r
./partitioned_matrix_view_test.cc:    srand(5);
./random.h:  srand(state);
./numeric_diff_test_utils.cc:  srand(random_seed_);
./gradient_checker_test.cc:  srand(5);
./normal_prior_test.cc:  srand(5);
./normal_prior_test.cc:  srand(5);
./corrector_test.cc:  srand(5);
./corrector_test.cc:  srand(5);
./gradient_checking_cost_function_test.cc:  srand(5);
./gradient_checking_cost_function_test.cc:  srand(5);
./rotation_test.cc:  srand(5);
./rotation_test.cc:  srand(5);
./rotation_test.cc:  srand(5);
./rotation_test.cc:  srand(5);
./rotation_test.cc:  srand(5);
./rotation_test.cc:  srand(5);
./gtest/gtest.h:// numbers with a uniform distribution.  Unlike rand() and srand(), it
./autodiff_test.cc:  srand(5);
./autodiff_test.cc:  srand(5);

in random.h
inline void SetRandomState(int state) {
  srand(state);
}

grep SetRandomState  . -r
./compressed_row_sparse_matrix_test.cc:  SetRandomState(29823);
./random.h:inline void SetRandomState(int state) {

**Comment by sandwichmaker** [comment]
@ahojnnes if you see sources of randomness in ceres, please point me to it. Threading should be the only source.

**Comment by ahojnnes** [comment]
@sandwhichmaker Threading is the source of randomness, but unless you go single threaded I don’t see a way to get around it.

**Comment by is03wlei** [comment]
@ahojnnes Did you mean these two lines?
https://github.com/colmap/colmap/blob/master/src/optim/bundle_adjustment.cc#L273
  solver_options.num_threads = 1;
  solver_options.num_linear_solver_threads = 1;

**Comment by ahojnnes** [comment]
You can just set ``--Mapper.num_threads 1`` and that should do the trick.

**Comment by is03wlei** [comment]
It seems Mapper.num_threads is not used because of the following fragment.

#ifdef OPENMP_ENABLED
  if (solver_options.num_threads <= 0) {
    solver_options.num_threads = omp_get_max_threads();
  }
  if (solver_options.num_linear_solver_threads <= 0) {
    solver_options.num_linear_solver_threads = omp_get_max_threads();
  }
#else
  solver_options.num_threads = 1;
  solver_options.num_linear_solver_threads = 1;
#endif

**Comment by ahojnnes** [comment]
@is03wlei This commit https://github.com/colmap/colmap/commit/cf7cf4ec856b3b7713fa1e30a0a032f40f7aec16 should fix the issue.

**Comment by ahojnnes** [comment]
Indeed, it worked before as well, but only with OpenMP, whole newer Ceres versions support different thread models as well.

**Comment by dklenke** [comment]
I am also trying to eliminate any randomness from the mapper and I set the seed as mentioned in the initial post and set `--Mapper.num_threads 1 `. Unfortunately I still get different results from repeated runs on the same dataset. Any ideas what I might be doing wrong?

**Comment by ahojnnes** [comment]
You have to manually set a fixed random seed using ``SetPRNGSeed()`` and ``srand()``.

**Comment by dklenke** [comment]
I set it like this in [random.cc](https://github.com/colmap/colmap/blob/dev/src/util/random.cc) :
`void SetPRNGSeed(unsigned seed) {
  // Overwrite existing PRNG
  if (PRNG != nullptr) {
    delete PRNG;
  }

  if (seed == kRandomPRNGSeed) {
    /*seed = static_cast<unsigned>(
        std::chrono::system_clock::now().time_since_epoch().count());*/
    seed = 0;
  }

  PRNG = new std::mt19937(seed);
  srand(seed);
}`
and also called SetPRNGSeed(0) at the beginning of the main function. Additionally I set every use of srand() I found outside of tests to srand(0). I still get different results.

**Comment by nbubis** [comment]
@dklenke - Did you ever solve this?

**Comment by umairharon** [comment]
Any way to setup the seed through the COLMAP parameters? every time I run COLMAP I have a different Point3D. Would you please advise?
