### ISSUE TITLE
fundamental matrix wrong?

### ISSUE THREAD

**Issue by bbzh** [colmap/colmap#430]
Hi Johannes,

I am trying to make use of the fundamental matrix returned from the feature matching stage. But when I verify it using the point-epipolar line distance, I found the error is in the order of thoousand.  Can suggest what is wrong here? Thanks.

**Comment by ahojnnes** [comment]
Where do you get the fundamental matrix from? The database or directly from the two view geometry object? Can you show a code sample please?

**Comment by bbzh** [comment]
I get it from the database. I modify the existing .py to read it from .db. Two relevant code are below:

   1. cursor.execute("SELECT pair_id, data, config, F  FROM inlier_matches "
                       "WHERE rows>=?;", (args.min_num_matches,))   
  2. F = np.fromstring(row[3],dtype=np.float64).reshape(-1,3)													
            fid.write("%d %.20f %.20f %.20f %.20f %.20f %.20f %.20f %.20f %.20f\n" %(row[2], F[0,0], F[0,1],F[0,2],F[1,0],F[1,1],F[1,2],F[2,0],F[2,1],F[2,2]))	

Looking forward to your reply again. Thanks

**Comment by ahojnnes** [comment]
There was a bug in how I wrote the data to the database, which should be fixed now with the following commit: https://github.com/colmap/colmap/commit/9f7065999f419e4283eac34adf49923c4d233361 - If you clear the two-view geometries in the database and re-run matching, then the data should be fixed. Can you report back whether it works now?

**Comment by bbzh** [comment]
I download the newest pre-built version 3.5 and, from scratch, do the feature extraction and matching and read F from database. It is still not correct.  Can you give feedback again? Thanks!

**Comment by ahojnnes** [comment]
@bbzh The table name from which you extract the data is still ``inlier_matches``?

**Comment by bbzh** [comment]
No. The new version does not contain inlier_matches in the table. Instead I extract from two_view_geometries. I check that F is valid in the sense of its rank 2, but it is not consistent with the keypoints in terms of epipolar constraint.

**Comment by ahojnnes** [comment]
Great, thanks for the update and for the bug report.
